export const FETCH_PROJECT_REQUEST='FETCH_PROJECT_REQUEST'
export const FETCH_PROJECT_SUCCESS='FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECT_FAILURE='FETCH_PROJECT_FAILURE'
export const GET_ERRORS='GET_ERRORS' 